### ISSUE TITLE
"namespace: true" writes an empty JSON object if there are no keys with a dot

### ISSUE THREAD

**Issue by barbogast** [bcabanes/gulp-angular-translate-extract#1]
First of all, great plugin, thanks a lot!

If I set `namespace: true` and don't have any keys containing dots (i.e. `A.B`) the written JSON-object is empty. When I add one key with a dot the JSON-object is written correctly.

**Comment by bcabanes** [comment]
Hi Koblaid,
The dot notation is quite formal and standard. It is one of the best way to describe namespaces. Maybe add an option to specify the namespace delimiter can be an eventuality.

++

**Comment by barbogast** [comment]
I mean something different.

If I process the following file...

``` javascript
$translate('ASDF')
```

...  with `namespace: false` I get the following expect output:

```
{
    "ASDF": ""
}
```

---

But with `namespace: true` the output is

```
{
}
```

I would expect it to be the same than with `namespace: false`, even though the key has no namespace.

Of course `namespace: true` could mean that using namespaced keys is requirement. Then a warning would be nice if keys without namespace are found. Maybe also mention it in the docs

**Comment by bcabanes** [comment]
Hi @Koblaid,
I now throw an error if the namespace's option is true and you have token with no dot `.`. Also update the readme.

Available in the new release v0.1.6.

++
