### ISSUE TITLE
Extract filters defined as one time binding

### ISSUE THREAD

**Issue by barbogast** [bcabanes/gulp-angular-translate-extract#3]
Angular allows filters to be defined as a one time binding:

``` html
<img src="..." alt="{{::('ALT_TEXT' | translate)}}"/>
```

See also here: http://stackoverflow.com/a/28590630/4287172

This is useful to prevent having too many watches open. gulp-angular-translate-extract doesn't seem to recognize these keys at the moment. Could you maybe add support for this kind of filters?

**Comment by bcabanes** [comment]
Hi @Koblaid,
I have added the regexp to support this, available in v0.1.7.

**Comment by barbogast** [comment]
Great, thanks.
